@baseURL = http://ticket-booth.com/api

### Get Current User
GET {{baseURL}}/users/currentuser HTTP/1.1

### Create New User
POST {{baseURL}}/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "forksofpower@gmail.com",
  "password": "12345678"
}