@baseURL = https://ticket-booth.example.com/api

###############################################################################
###
### Authentication
###
###############################################################################

### Create a Random New User
POST {{baseURL}}/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "{{$guid}}@gmail.com",
  "password": "12345678"
}

### Create a New User
POST {{baseURL}}/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "forksofpower@gmail.com",
  "password": "12345678"
}

### Sign-In User
POST {{baseURL}}/users/signin HTTP/1.1
Content-Type: application/json

{
  "email": "forksofpower@gmail.com",
  "password": "12345678"
}

### Get Current User
GET {{baseURL}}/users/currentuser HTTP/1.1

### Update Current User
PATCH {{baseURL}}/users/currentuser HTTP/1.1
Content-Type: application/json

{
  "firstName": "Forks",
  "lastName": "Of Power"
}

### Sign-Out Current User
GET {{baseURL}}/users/signout HTTP/1.1


###############################################################################
###
### Tickets
###
###############################################################################

### Create Ticket
POST {{baseURL}}/tickets HTTP/1.1
Content-Type: application/json

{
  "title": "Concert",
  "price": 20
}

### Get All Tickets
GET {{baseURL}}/tickets HTTP/1.1

### Get Ticket by ID

@ticketId = 64f94598acab320650c8eb53
GET {{baseURL}}/tickets/{{ticketId}} HTTP/1.1

### Update Ticket
PUT {{baseURL}}/tickets/{{ticketId}} HTTP/1.1
Content-Type: application/json

{
  "title": "Concert",
  "price": 15
}

### Delete Ticket
DELETE {{baseURL}}/tickets/{{ticketId}} HTTP/1.1

###############################################################################
###
### Orders
###
###############################################################################

### Create Order
POST {{baseURL}}/orders HTTP/1.1
Content-Type: application/json

{
  "ticketId": "{{ticketId}}"
}

### Get All Orders
GET {{baseURL}}/orders HTTP/1.1

### Get Order by ID
# @orderId = response.body.id
@orderId = 64f945a733efcd9f20e9d281
GET {{baseURL}}/orders/{{orderId}} HTTP/1.1

### Delete Order
DELETE {{baseURL}}/orders/{{orderId}} HTTP/1.1

###############################################################################
###
### Payments
###
###############################################################################
### Create Payment
POST {{baseURL}}/payments HTTP/1.1
Content-Type: application/json

{
  "token": "tok_visa",
  "orderId": "{{orderId}}"
}
