@baseURL = https://ticket-booth.example.com/api

### Create a Random New User
POST {{baseURL}}/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "{{$guid}}@gmail.com",
  "password": "12345678"
}

### Create a New User
POST {{baseURL}}/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "forksofpower@gmail.com",
  "password": "12345678"
}

### Sign-In User
POST {{baseURL}}/users/signin HTTP/1.1
Content-Type: application/json

{
  "email": "forksofpower@gmail.com",
  "password": "12345678"
}

### Get Current User
GET {{baseURL}}/users/currentuser HTTP/1.1

### Sign-Out Current User
GET {{baseURL}}/users/signout HTTP/1.1