apiVersion: skaffold/v4beta6
kind: Config

manifests:
  rawYaml:
    - infra/k8s/*
deploy:
  kubectl: {}

# custom
.YamlAnchors:
  common:
    - &prod-artifact
      docker:
        target: production
        dockerfile: ../../infra/docker/service.Dockerfile
    - &dev-artifact
      docker:
        target: development
        dockerfile: ../../infra/docker/service.Dockerfile
      sync:
        manual:
          - src: "**/*.{ts,js,json,tsx,jsx}"
            dest: "app/"
  artifactDefaults:
    - &AUTH_SERVICE
      image: forksofpower/tb-auth
      context: services/auth

    - &CLIENT_SERVICE
      image: forksofpower/tb-client
      context: services/client

    - &TICKETS_SERVICE
      image: forksofpower/tb-tickets
      context: services/tickets

    - &PAYMENTS_SERVICE
      image: forksofpower/tb-payments
      context: services/payments

    - &EXPIRATION_SERVICE
      image: forksofpower/tb-expiration
      context: services/expiration

    - &ORDERS_SERVICE
      image: forksofpower/tb-orders
      context: services/orders

# production
build:
  local:
    push: false
  artifacts:
    - <<: [*AUTH_SERVICE, *prod-artifact]
    - <<: [*CLIENT_SERVICE, *prod-artifact]
    - <<: [*TICKETS_SERVICE, *prod-artifact]
    - <<: [*PAYMENTS_SERVICE, *prod-artifact]
    - <<: [*EXPIRATION_SERVICE, *prod-artifact]
    - <<: [*ORDERS_SERVICE, *prod-artifact]

# development
profiles:
  - name: dev
    activation:
      - command: dev
    build:
      local:
        push: false
      artifacts:
        - <<: [*AUTH_SERVICE, *dev-artifact]
        - <<: [*CLIENT_SERVICE, *dev-artifact]
        - <<: [*TICKETS_SERVICE, *dev-artifact]
        - <<: [*PAYMENTS_SERVICE, *dev-artifact]
        - <<: [*EXPIRATION_SERVICE, *dev-artifact]
        - <<: [*ORDERS_SERVICE, *dev-artifact]
