@baseURL = https://ticket-booth.example.com/api

### Create a New User
POST {{baseURL}}/users/signup HTTP/1.1
Content-Type: application/json

{
  "email": "forksofpower@gmail.com",
  "password": "12345678"
}


### Create Ticket
# @name createTicket
POST {{baseURL}}/tickets HTTP/1.1
Content-Type: application/json

{
  "title": "Concert",
  "price": 20
}

### Update Ticket
@ticketId = {{createTicket.response.body.id}}
PUT {{baseURL}}/tickets/{{ticketId}} HTTP/1.1
Content-Type: application/json

{
  "title": "Concert",
  "price": 15
}

### Create Order
# @name createOrder
POST {{baseURL}}/orders HTTP/1.1
Content-Type: application/json

{
  "ticketId": "{{ticketId}}"
}

### Get Order by ID
@orderId = {{createOrder.response.body.id}}
GET {{baseURL}}/orders/{{orderId}} HTTP/1.1

### Delete Order (Cancel Order)
DELETE {{baseURL}}/orders/{{orderId}} HTTP/1.1


### Create Payment
# @name createPayment
POST {{baseURL}}/payments HTTP/1.1
Content-Type: application/json

{
  "token": "tok_visa",
  "orderId": "{{orderId}}"
}