apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
        - name: payments
          image: forksofpower/tb-payments
          resources:
            limits:
              memory: "1Gi"
              cpu: "1.0"
          env:
            - name: PORT
              value: "4000"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: nats://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: ticketbooth
            - name: MONGO_URI
              value: mongodb://payments-mongo-srv:27017/payments
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 4000
      targetPort: 4000
